language: node_js
node_js:
  - 13

sudo: required

services:
  - docker

before_install:
  - docker build -t tarabyte/animated-palm-tree -f Dev.Dockerfile .

script:
  - docker run tarabyte/animated-palm-tree CI=true yarn test
