language: node_js
node_js:
  - 13

sudo: required

services:
  - docker

before_install:
  - docker build -t tarabyte/animated-palm-tree -f Dev.Dockerfile .

script:
  - docker run -e CI=true tarabyte/animated-palm-tree yarn test
