version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - 8001:3000
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
